modLoader="javafml"
loaderVersion="[40,)"
license="CC-BY-SA-4.0"
[[mods]]
modId="hitindication"
version="1.2.2"
displayName="Hit Indication"
logoFile="Hit_Indication.png"
credits="Thank you HaHaWTH, Emik, Enitoni, Lily for localizations"
authors="Hamester and Axovoxel"
description="Adds configurable hit indicators."
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
