modLoader="javafml"
loaderVersion="[36,)"
license="CC-BY-SA-4.0"
[[mods]]
modId="hitindication"
version="1.2.1"
displayName="Hit Indication"
logoFile="Hit_Indication.png"
credits="HaHaWTH for zh_cn localization"
authors="Hamester and Axovoxel"
description="Adds configurable hit indicators."
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
